export const MOTIVATING_MESSAGES = [
  "Nice one, {name}! Every tracked expense is a victory.",
  "Boom! Another win for Team {name}.",
  "You did it again, {name}! Consistency pays—literally.",
  "You're crushing it, {name}! Financial freedom is waving at you.",
  "Another step closer to your goals, {name}. Keep that fire!",
  "Budget boss move, {name}! Keep that streak alive.",
  "Money managed. Confidence earned. Well done, {name}!",
  "Saving spree activated, {name}. Keep stacking those wins!",
  "{name}, you're proof that small steps lead to big change.",
  "Cha-ching! That's the sound of progress, {name}.",
  "Stay in the game, {name}. Millionaires are made one log at a time.",
  "Discipline beats motivation, and you've got both, {name}.",
  "Keep going, {name}—your future self will thank you.",
  "Progress is quiet, {name}. But it's happening every time you log.",
  "{name}, remember: budgets build freedom, not limits.",
  "You're not tracking money, {name}—you're tracking power.",
  "Keep that momentum, {name}. Habits make heroes.",
  "Stay focused, {name}. Wealth loves attention.",
  "Every log is a lesson, {name}. You're getting sharper.",
  "Step by step, {name}. Slow money is smart money.",
  "Nice! Somewhere, your future accountant is smiling, {name}.",
  "{name}, you just made your wallet 0.3% happier.",
  "Good job, {name}! Your inner adult is proud (and shocked).",
  "Keep it up, {name}—you're one log away from a Netflix documentary.",
  "{name}, that's another 'responsible adult' achievement unlocked.",
  "Budgeting level: Jedi Master. Way to go, {name}.",
  "Money moves made! Beyoncé would approve, {name}.",
  "Hey {name}, your wallet called—said it's feeling safer already.",
  "Look at you, {name}, adulting like a pro.",
  "Cash discipline: 100%. Impulse shopping: -100%. Nice one, {name}.",
  "Balance looks good on you, {name}.",
  "Small actions. Big outcomes. Keep your calm, {name}.",
  "{name}, you're not just saving money—you're shaping habits.",
  "Peace of mind starts with numbers in line. Good work, {name}.",
  "Clarity is wealth, {name}. Keep tracking your way to calm.",
  "Each log is a moment of mindfulness, {name}.",
  "Stay patient, {name}. Compound progress is invisible—until it's not.",
  "You're mastering control, {name}. That's real wealth.",
  "Every entry is proof of self-respect, {name}.",
  "Good things take time, {name}. You're on the right track.",
  "No excuses, {name}. You're doing what most won't.",
  "Keep pushing, {name}. Discipline is your superpower.",
  "{name}, winners track. Losers guess.",
  "Feel that? That's the sound of accountability, {name}.",
  "Logging even the small stuff? That's elite mindset, {name}.",
  "One more log, one less regret, {name}.",
  "Stay ruthless with your habits, {name}.",
  "Comfort won't build wealth, {name}. Action will.",
  "Track. Adjust. Dominate. Repeat, {name}.",
  "Keep showing up, {name}. Success is boring—and that's the point."
];

export function getRandomMotivationalMessage(name: string): string {
  const randomIndex = Math.floor(Math.random() * MOTIVATING_MESSAGES.length);
  return MOTIVATING_MESSAGES[randomIndex].replace(/{name}/g, name);
}

